-- MySQL Script generated by MySQL Workbench
-- Tue Jun  2 19:18:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tema_pw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tema_pw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tema_pw` DEFAULT CHARACTER SET utf8 ;
USE `tema_pw` ;

-- -----------------------------------------------------
-- Table `tema_pw`.`utilizator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tema_pw`.`utilizator` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `parola` VARCHAR(256) NOT NULL,
  `privilegii` TINYINT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tema_pw`.`articol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tema_pw`.`articol` (
  `id_articol` INT NOT NULL AUTO_INCREMENT,
  `nume_articol` VARCHAR(256) NOT NULL,
  `cale_resursa` VARCHAR(256) NOT NULL,
  `data_creeat` DATE NOT NULL,
  `data_modificat` DATE NOT NULL,
  PRIMARY KEY (`id_articol`),
  UNIQUE INDEX `id_articol_UNIQUE` (`id_articol` ASC) VISIBLE,
  UNIQUE INDEX `nume_articol_UNIQUE` (`nume_articol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tema_pw`.`sectiune`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tema_pw`.`sectiune` (
  `id_sectiune` INT NOT NULL AUTO_INCREMENT,
  `id_articol` INT NOT NULL,
  `nume_sectiune` VARCHAR(256) NOT NULL,
  `cale_continut` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_sectiune`, `id_articol`),
  UNIQUE INDEX `id_sectiune_UNIQUE` (`id_sectiune` ASC) VISIBLE,
  UNIQUE INDEX `nume_sectiune_UNIQUE` (`nume_sectiune` ASC) VISIBLE,
  INDEX `fk_sectiune_articol_idx` (`id_articol` ASC) VISIBLE,
  CONSTRAINT `fk_sectiune_articol`
    FOREIGN KEY (`id_articol`)
    REFERENCES `tema_pw`.`articol` (`id_articol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tema_pw`.`modificare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tema_pw`.`modificare` (
  `id_modif` INT NOT NULL AUTO_INCREMENT,
  `opcode` INT NOT NULL,
  `data_modificat` DATE NOT NULL,
  `id_user` INT NOT NULL,
  `id_sectiune` INT NOT NULL,
  `id_articol` INT NOT NULL,
  PRIMARY KEY (`id_modif`),
  UNIQUE INDEX `id_modif_UNIQUE` (`id_modif` ASC) VISIBLE,
  INDEX `fk_modificare_utilizator1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_modificare_sectiune1_idx` (`id_sectiune` ASC, `id_articol` ASC) VISIBLE,
  CONSTRAINT `fk_modificare_utilizator1`
    FOREIGN KEY (`id_user`)
    REFERENCES `tema_pw`.`utilizator` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_modificare_sectiune1`
    FOREIGN KEY (`id_sectiune` , `id_articol`)
    REFERENCES `tema_pw`.`sectiune` (`id_sectiune` , `id_articol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
